name: Run unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/chekout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run test